### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Xemnes-Keyethkateth** [Buuz135/Portality#62]
I can see that other people can run the mod but no matter what I do even if only portality and 	Titanium is installed game will crash on startup.

Paste bin of the crash log can be found here
https://pastebin.com/6Um1EMS3

**Comment by Buuz135** [comment]
Try redownloading the mod

**Comment by frakier** [comment]
No mods just
forge-1.14.4-28.1.68-installer
portality-1.14.4-2.0.4-b0b3467
titanium-1.14.4-2.2.0-d9775a7.jar
...
"Caused by: net.minecraftforge.fml.ModLoadingException: Portality has class loading errors
ยง7com.hrznstudio.titanium.network.NetworkHandler.<init>(Ljava/lang/String;)V
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.<init>(FMLModContainer.java:77)"
...
[crash-2019-10-26_19.05.45-client.txt](https://github.com/InnovativeOnlineIndustries/Portality/files/3775346/crash-2019-10-26_19.05.45-client.txt)

**Comment by Buuz135** [comment]
Both of you should update titanium

**Comment by frakier** [comment]
updated it and updated my report, still have the error.
attached the newest crash report, i'll add a a suitably obfuscated debug.log as well...
[debug.log](https://github.com/InnovativeOnlineIndustries/Portality/files/3775349/debug.log)

**Comment by Buuz135** [comment]
Update to the latest beta

**Comment by frakier** [comment]
portality-1.14.4-2.0.4-b0b3467.jar
titanium-1.14.4-2.2.5.jar
forge-1.14.4-28.1.68-installer

loaded without crashing... now to try with the menagerie of mods.
